name: Deploy to Remote VM

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH for connecting to the remote VM
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Transfer files to the VM via SCP or run commands directly via SSH
      - name: Deploy Application to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            cd /path/to/your/application
            git pull origin main
            # If you are using Docker, you can rebuild and restart your container
            docker-compose down
            docker-compose up -d --build
          EOF
