name: CD Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
          docker stop communitysmells || true
          docker rm communitysmells || true
          docker run -d --name communitysmells -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
