name: CD Pipeline

on:
  push:
    branches:
      - main # Deploy on pushes to main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted # Make sure the self-hosted runner is installed on your VM

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull the latest Docker image and run it
      - name: Deploy Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
          docker stop communitysmells || true
          docker rm communitysmells || true
          docker run -d --name communitysmells -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
