name: CD Pipeline

on:
  push:
    branches:
      - main
      - feature ci-cd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Decode the Base64-encoded SSH key and save it as a file
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.VM_SSH_KEY_BASE64 }}" | base64 -d > /tmp/vm_ssh_key
          chmod 600 /tmp/vm_ssh_key

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key_path: /tmp/vm_ssh_key
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
            docker stop communitysmells || true
            docker rm communitysmells || true
            docker run -d --name communitysmells -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
