name: CD Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd  # Include any branches you'd like to test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Decode the Base64-encoded SSH key and save it in a stable directory within the runner
      - name: Prepare SSH Key
        run: |
          mkdir -p ~/course-project-g01/actions-runner/.ssh
          echo "${{ secrets.VM_SSH_KEY_BASE64 }}" | base64 -d > ~/course-project-g01/actions-runner/.ssh/vm_ssh_key
          chmod 600 ~/course-project-g01/actions-runner/.ssh/vm_ssh_key

      # Debugging step to confirm that the SSH key file was created successfully
      - name: Confirm SSH Key File
        run: |
          echo "Listing contents of the .ssh directory:"
          ls -la ~/course-project-g01/actions-runner/.ssh
          echo "Displaying SSH key contents for debugging (securely check this line only if necessary):"
          cat ~/course-project-g01/actions-runner/.ssh/vm_ssh_key

      # Deploy to the server using the SSH key
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key_path: ~/course-project-g01/actions-runner/.ssh/vm_ssh_key  # Absolute path to SSH key in runner
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
            docker stop communitysmells || true
            docker rm communitysmells || true
            docker run -d --name communitysmells -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
