name: CD Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd # Trigger deployment on pushes to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted # Ensure this runner is installed on the target VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull the latest Docker image and run it
      - name: Deploy Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
          docker stop communitysmells || true
          docker rm communitysmells || true
          docker run -d --name communitysmells -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
