name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
      - feature/ci-cd
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build and tag the Docker image as 'latest'
      - name: Build and Tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest .

      # Step 4: Push the Docker image to Docker Hub with 'latest' tag
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/communitysmells:latest
