name: Flake8 Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-lint:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run black on the whole project
      - name: Run Black
        run: |
          python -m black .

      # Step 5: Run isort on the whole project
      - name: Run Isort
        run: |
          python -m isort .

      # Step 6: Run Flake8 using the config file from .github/workflows
      - name: Run Flake8
        run: |
          flake8 --config=.github/workflows/.flake8 .
