name: Flake8 Linting

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - main
      - development
      - cs_detector
      - dev
      - "feature/*"
      - "refactor/*"
      - resultsPdf_generation
      - smellDetectionAndDocGenApi
      - saikat-br
  pull_request:
    branches:
      - main
      - development

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.12.4 environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      # Step 3: Install dependencies, including flake8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Flake8 with custom configuration file path
      - name: Run Flake8
        run: |
          flake8 --config=.github/workflows/.flake8 .

